server:
  port: 8001
spring:
  application:
    name: service-product
  datasource:
    # driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/meals?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 显示ip和端口号
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
